### PR TITLE
Set up starter code for backend

### PR DESCRIPTION
**Pull request by benlin-gan**
I added code that implements the core of a web server in rust. It uses the networking primitives from the rust standard library to listen for incoming tcp requests on localhost, and sends back the contents of an html file.

### CODE REVIEW

**Comment by franklinzhang12** [comment]
Runs fine on MacOS, but upon trying to view the webpage (localhost:7878), the program crashes with the following message:
`thread 'main' panicked at src/main.rs:26:53:
called Result::unwrap() on an Err value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
note: run with RUST_BACKTRACE=1 environment variable to display a backtrace`

**Comment by benlin-gan** [comment]
Alright I think I fixed the issue, it was because of a bad filepath. Can you try it again?

**Comment by franklinzhang12** [comment]
Thanks, it works now.

**Review by franklinzhang12 — APPROVED** [review]
Looks good, issues were fixed and it now runs properly.

**Pull request merged**
